data:
  raw_path: "data/raw/train.csv"
  test_size: 0.2

features:
  numerical:
    - "trip_distance"
    - "passenger_count"
    - "pickup_hour_of_day"
    - "pickup_day_of_year"
  categorical:
    - "is_anomaly"
    - "pickup_day_of_week"
    - "traffic_congestion"
    - "pickup_near_airport"
    - "dropoff_near_airport"